export const ROUTES = {
  HOME: "/home",
  FOODS: "/foods",
  FAVORITE_FOODS: "/favorite-foods",
  FAVORITE_FOOD_DETAILS: "/favorite-food-details",
  CREATE_FOOD: "/create-food",
  FOOD_DETAILS: "/food-details",
  RECIPE_NUTRITION_CALCULATOR: "/recipe-nutrition-calculator",
  MEALS: "/meals",
  RECIPES: "/recipes",
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  PROFILE: "/profile",
};
